name: Build APK

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checar código
        uses: actions/checkout@v4

      - name: Instalar dependências do sistema
        run: |
          sudo apt update
          sudo apt install -y python3-pip ffmpeg libncurses-dev libffi-dev libssl-dev libnss3 unzip curl openjdk-11-jdk maven

      - name: Instalar JAXB
        run: |
          sudo apt install -y libjaxb-api-java libjaxb-impl-java

      - name: Instalar Buildozer
        run: |
          pip install --upgrade cython
          pip install buildozer

      - name: Baixar e Instalar Android SDK Completo
        run: |
          # Baixar o SDK completo, incluindo todas as ferramentas necessárias
          mkdir -p $HOME/android-sdk
          cd $HOME/android-sdk
          
          # Baixar a versão mais recente do Android SDK (instalador completo)
          curl -o android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
          unzip android-sdk.zip -d $HOME/android-sdk
          rm android-sdk.zip
          
          # Verificar se sdkmanager foi extraído corretamente
          if [ ! -f "$HOME/android-sdk/tools/bin/sdkmanager" ]; then
            echo "Erro: sdkmanager não encontrado!"
            exit 1
          fi

          # Adicionar sdkmanager ao PATH
          echo "$HOME/android-sdk/tools/bin" >> $GITHUB_PATH
          echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH

          # Configurar variáveis de ambiente
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV

          # Instalar pacotes essenciais do SDK
          $HOME/android-sdk/tools/bin/sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;33.0.2"

          # Aceitar licenças do SDK
          yes | $HOME/android-sdk/tools/bin/sdkmanager --licenses

      - name: Verificar instalação do AIDL e SDK
        run: |
          echo "Verificando a instalação do AIDL..."
          
          # Verificar se o AIDL foi instalado corretamente
          if [ ! -f "$ANDROID_HOME/build-tools/33.0.2/aidl" ]; then
            echo "Erro: AIDL não encontrado! Instalando novamente..."
            $HOME/android-sdk/tools/bin/sdkmanager --install "build-tools;33.0.2"
          else
            echo "AIDL encontrado em: $ANDROID_HOME/build-tools/33.0.2/aidl"
          fi
          
          # Verificar se sdkmanager está funcionando
          echo "Verificando se sdkmanager funciona corretamente..."
          if ! $HOME/android-sdk/tools/bin/sdkmanager --list; then
            echo "Erro: sdkmanager falhou ao listar os pacotes!"
            exit 1
          fi

      - name: Construir o APK
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/33.0.2:$PATH
          
          # Log para verificar o caminho do SDK
          echo "Caminho do SDK: $ANDROID_HOME"
          
          buildozer -v android debug

      - name: Fazer upload do APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: bin/*.apk
