name: Build APK

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checar código
        uses: actions/checkout@v4

      - name: Instalar dependências do sistema
        run: |
          sudo apt update
          sudo apt install -y python3-pip ffmpeg libncurses-dev libffi-dev libssl-dev libnss3 unzip

      - name: Instalar Buildozer
        run: |
          pip install --upgrade cython
          pip install buildozer

      - name: Instalar Android SDK
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          curl -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip sdk-tools.zip -d latest
          rm sdk-tools.zip

      - name: Configurar variáveis de ambiente do Android SDK
        run: |
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH
          echo "$ANDROID_HOME/build-tools/33.0.2" >> $GITHUB_PATH

      - name: Aceitar todas as licenças do SDK
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true

      - name: Instalar Build-Tools e AIDL
        run: |
          sdkmanager --install "build-tools;33.0.2" "platform-tools" "platforms;android-34"
          sdkmanager --install "platform-tools" "platforms;android-34" "sources;android-34"
          sdkmanager --install "build-tools;33.0.2" "aidl" --verbose
          yes | sdkmanager --licenses || true  

      - name: Verificar se AIDL está instalado corretamente
        run: |
          if [ ! -f "$ANDROID_HOME/build-tools/33.0.2/aidl" ]; then
            echo "Erro: AIDL não encontrado!"
            exit 1
          else
            echo "AIDL encontrado em: $ANDROID_HOME/build-tools/33.0.2/aidl"
          fi

      - name: Construir o APK
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/33.0.2:$PATH
          buildozer -v android debug

      - name: Fazer upload do APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: bin/*.apk
