name: Build APK with Gradle

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checar código
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: |
          sudo apt update
          sudo apt install -y openjdk-8-jdk wget unzip curl

      - name: Instalar Gradle
        run: |
          # Baixar e configurar o Gradle
          wget https://services.gradle.org/distributions/gradle-7.4.2-bin.zip
          unzip gradle-7.4.2-bin.zip
          sudo mv gradle-7.4.2 /opt/gradle
          echo "export PATH=$PATH:/opt/gradle/bin" >> ~/.bashrc
          source ~/.bashrc

      - name: Configurar JDK
        run: |
          export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
          echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV

      - name: Baixar e instalar o Android SDK
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          unzip commandlinetools.zip -d $HOME/android-sdk/cmdline-tools
          rm commandlinetools.zip

          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
          echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH

      - name: Aceitar Licenças do SDK
        run: |
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Construir o APK com Gradle
        run: |
          # Acesse o diretório do seu projeto Android
          cd path/to/your/project

          # Executar Gradle para construir o APK
          ./gradlew assembleRelease

      - name: Fazer upload do APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/*.apk
