name: Build APK

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checar código
        uses: actions/checkout@v4

      - name: Instalar dependências do sistema
        run: |
          sudo apt update
          sudo apt install -y python3-pip ffmpeg libncurses-dev libffi-dev libssl-dev libnss3 unzip

      - name: Instalar Buildozer
        run: |
          pip install --upgrade cython
          pip install buildozer

      - name: Instalar versão compatível do Android Build-Tools
        run: |
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "build-tools;33.0.2"
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses    

      - name: Aceitar licenças do Android SDK
        run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Construir o APK
        run: |
          buildozer -v android debug

      - name: Fazer upload do APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: bin/*.apk
