name: Build APK

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checar código
        uses: actions/checkout@v4

      - name: Instalar dependências do sistema
        run: |
          sudo apt update
          sudo apt install -y python3-pip ffmpeg libncurses-dev libffi-dev libssl-dev libnss3 unzip curl openjdk-8-jdk

      - name: Configurar JDK 8
        run: |
          # Definir as variáveis de ambiente para o JDK 8
          export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
          export PATH=$JAVA_HOME/bin:$PATH
          echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV
          echo "PATH=$PATH" >> $GITHUB_ENV

      - name: Baixar e Instalar Android SDK Command-line Tools
        run: |
          mkdir -p $HOME/android-sdk
          cd $HOME/android-sdk
          
          # Baixar e extrair o SDK Command-Line Tools
          curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          unzip commandlinetools.zip -d $HOME/android-sdk
          rm commandlinetools.zip
          
          # Verificar se sdkmanager foi instalado corretamente
          if [ ! -f "$HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager" ]; then
            echo "Erro: sdkmanager não encontrado!"
            ls -la $HOME/android-sdk/cmdline-tools/latest/bin/
            exit 1
          fi
          echo "sdkmanager encontrado em: $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager"

          # Adicionar sdkmanager ao PATH
          echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH

          # Configurar variáveis de ambiente
          echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV

      - name: Aceitar Licenças do Android SDK
        run: |
          echo "Aceitando as licenças..."
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Instalar Buildozer
        run: |
          pip install --upgrade cython
          pip install buildozer

      - name: Instalar pacotes essenciais do SDK
        run: |
          # Instalar pacotes essenciais do SDK, incluindo uma versão estável do build-tools
          echo "Instalando pacotes do SDK..."
          $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;33.0.2"

      - name: Verificar SDK
        run: |
          # Verificar se sdkmanager está funcionando corretamente
          echo "Verificando sdkmanager..."
          if ! $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --list; then
            echo "Erro: sdkmanager falhou ao listar os pacotes!"
            exit 1
          fi

      - name: Construir o APK
        run: |
          echo "Construindo o APK..."
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/33.0.2:$PATH
          echo "Caminho do SDK: $ANDROID_HOME"
          buildozer -v android debug

      - name: Fazer upload do APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: bin/*.apk
